kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: deploy
    image: docker
    environment:
      EXCHANGE_RATES_BASE_URL:
        from_secret: EXCHANGE_RATES_BASE_URL
      EXCHANGE_RATES_TOKEN:
        from_secret: EXCHANGE_RATES_TOKEN
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker compose build
      - docker compose up -d --force-recreate

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
