services:
  xrates:
    image: fullstacklab/xrates
    container_name: xrates
    restart: unless-stopped
    network_mode: traefik
    environment:
      - EXCHANGE_RATES_BASE_URL=${EXCHANGE_RATES_BASE_URL}
      - EXCHANGE_RATES_TOKEN=${EXCHANGE_RATES_TOKEN}
    labels:
      traefik.enable: true
      traefik.http.services.xrates.loadbalancer.server.port: 3000
      traefik.http.routers.xrates.rule: Host(`xrates.fullstacklab.org`)
      traefik.http.routers.xrates.entrypoints: https
      traefik.http.routers.xrates.tls.certresolver: letsencrypt
